- name: Create clients directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - client-configs/keys
    - client-configs/files

- name: Find all private keys
  find:
    paths: /usr/share/easy-rsa/pki/private/
    patterns: '*.key'
    excludes: 
      - 'server.key'
      - 'ca.key'
  register: found_keys

- set_fact:
    found_keys_files: "{{ found_keys.files | map(attribute='path') | map('basename')  }}"

- name: convert array
  set_fact:
    converted_arr: "{{ clients | map('regex_replace', '^(.*)@.*$', '\\1.key') | list }}"

- name: convert array
  set_fact:
    client_arr: "{{ clients | map('regex_replace', '^(.*)@.*$', '\\1') | list }}"

- name: convert array to dict
  set_fact:
    email_dict: "{{ clients | map('regex_replace', '^(.*)@.*$', '\\1') | zip(clients) | community.general.dict }}"

- name: revoke clients array
  set_fact:
    revoke_arr: "{{ found_keys_files | difference(converted_arr)  | map('regex_replace', '^(.*).key$', '\\1') | list }}"

- name: add new clients array
  set_fact:
    new_clients_arr: "{{ converted_arr | difference(found_keys_files) | map('regex_replace', '^(.*).key$', '\\1') | list  }}"


- name: revoke certs
  shell: 
    chdir: /usr/share/easy-rsa/
    cmd: "./easyrsa revoke {{ item }}"
  with_items: "{{ revoke_arr }}"
  notify:
    - restart openvpn

- name: Delete OVPN revoked files
  shell: 
    chdir: client-configs/files
    cmd: "rm -f {{ item }}-{{server_prefix}}.ovpn"
  with_items: "{{ revoke_arr }}"

- name: update CRL
  shell: 
    chdir: /usr/share/easy-rsa/
    cmd: ./easyrsa gen-crl

- name: Copy crl key
  copy:
    src: "/usr/share/easy-rsa/pki/crl.pem"
    dest: /etc/openvpn/server/
    remote_src: yes
- name: certs for new users
  shell: 
    chdir: /usr/share/easy-rsa/
    cmd: "./easyrsa --batch --days=3650 build-client-full {{item}} nopass"
  with_items: "{{ new_clients_arr }}"

- name: Find actuate private keys
  find:
    paths: /usr/share/easy-rsa/pki/private/
    patterns: '*.key'
    excludes: 
      - 'server.key'
      - 'ca.key'
  register: found_keys_actuate

- name: Copy profile script key
  copy:
    src: "/usr/share/easy-rsa/pki/crl.pem"
    dest: /etc/openvpn/server/
    remote_src: yes

- name: Copy client config
  template:
    src: client.conf.j2
    dest: client-configs/base.conf

- name: Copy profile script key
  copy:
    src: gen_openvpn_profile.sh
    dest: client-configs/

- name: Generate Profile files
  shell: "bash client-configs/gen_openvpn_profile.sh {{ item }} {{server_prefix}}"
  with_items: "{{ found_keys_actuate.files | map(attribute='path') | map('basename') | map('regex_replace', '^(.*).key$', '\\1') | list }}"

- name: Send e-mail to a bunch of users, attaching files
  community.general.mail:
    host: "{{ smtp.host }}"
    port: "{{ smtp.port }}"
    username: "{{ smtp.username }}"
    password: "{{ lookup('ansible.builtin.env', 'MAIL_PASS') }}"
    to: "No-replay-IDS <{{ email_dict[item] }}>"
    subject: OpenVPN
    body: Your VPN
    from: infra-ids-no-reply@idynsys.org (infra-ids-no-reply)
    attach:
    - "client-configs/files/{{ item }}-{{ server_prefix }}.ovpn"
  with_items: "{{ new_clients_arr }}"
